// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUUI8nFFp1kB15ONNRCNlmVUYRYO-yGqQ',
    appId: '1:493329751371:web:b132fca4633b9dc7cddcce',
    messagingSenderId: '493329751371',
    projectId: 'pagpou-sts',
    authDomain: 'pagpou-sts.firebaseapp.com',
    databaseURL: 'https://pagpou-sts-default-rtdb.firebaseio.com',
    storageBucket: 'pagpou-sts.appspot.com',
    measurementId: 'G-TB7W6CYDSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBBHTuXzeDXSkF2ciS98vM7Y5vHfLsAp0',
    appId: '1:493329751371:android:176e5ec75125eb0bcddcce',
    messagingSenderId: '493329751371',
    projectId: 'pagpou-sts',
    databaseURL: 'https://pagpou-sts-default-rtdb.firebaseio.com',
    storageBucket: 'pagpou-sts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRFJoWx8lsUHOEuC8Wsv6gT4nyzP48SPs',
    appId: '1:493329751371:ios:6efc7aa7a304b928cddcce',
    messagingSenderId: '493329751371',
    projectId: 'pagpou-sts',
    databaseURL: 'https://pagpou-sts-default-rtdb.firebaseio.com',
    storageBucket: 'pagpou-sts.appspot.com',
    androidClientId: '493329751371-1h561snpk3a1q3d981ikaaj3vt6rrq1k.apps.googleusercontent.com',
    iosClientId: '493329751371-pnodjqueat9sd724lke9jtigqn6pcf65.apps.googleusercontent.com',
    iosBundleId: 'com.example.xtudo',
  );
}
